openapi: 3.0.0
info:
  version: 1.0.0
  title: Swagger EmployeeList
host: localhost:3002 
schemes:
  - http
  - https
consumes:
  - application/json
paths:
/api/auth/signup:
  post:
    summary: "Create user"
    parameters:
      - name: name
        in: body
        description: "name of user."
        required: true
        schema:
          type: string
      - name: email
        in: body
        description: "email of user"
        required: true
        schema:
          type: string
      - name: password
        in: body
        description: "password of user"
        required: true
        schema:
          type: string
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                default: "Max"
              email:
                type: string
                default: "max1234@gmail.com"
              password:
                type: string
                default: "12max34"
            required:
              - password
    responses:
      "200":
        description: successful operation
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: number
                    example: 4011,
                  name:
                    type: string
                    example: "Max"
                  email:
                    type: string
                    example: "max1234@gmail.com"
                  password:
                    type: string
                    example: "12max34"

      "404":
        description: No matching record found for the given criteria.
